[tool.poetry]
name = "slack-bot-openai"
version = "0.1.0"
description = ""
authors = ["AlanBustamanteRemerge <alan.bustamante@remerge.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
